# 全局科室映射标准 (Global Department Mapping Standard)

DEPARTMENT_MAPPING = {
    # P0 强制映射：药剂、遗传、精准医学 -> 药剂科_精准医学
    "药剂科": "药剂科_精准医学",
    "遗传咨询科": "药剂科_精准医学",
    "精准医学科": "药剂科_精准医学",
    "Pharmacogenomics": "药剂科_精准医学",
    
    # 标准科室映射
    "儿科": "儿科",
    "Pediatrics": "儿科",
    "妇科": "妇产科",
    "产科": "妇产科",
    "妇产科": "妇产科",
    "Gynecology": "妇产科",
    "Obstetrics": "妇产科",
    "内科": "内科",
    "Internal Medicine": "内科",
    "外科": "外科",
    "Surgery": "外科",
    "普通外科": "普通外科",
    "General Surgery": "普通外科",
    "皮肤科": "皮肤科",
    "Dermatology": "皮肤科",
    "骨科": "骨科",
    "Orthopedics": "骨科",
    "眼科": "眼科",
    "Ophthalmology": "眼科",
    "耳鼻喉科": "耳鼻喉科",
    "ENT": "耳鼻喉科",
    "口腔科": "口腔科",
    "Stomatology": "口腔科",
    "泌尿科": "泌尿外科",
    "泌尿外科": "泌尿外科",
    "Urology": "泌尿外科",
    "消化内科": "消化内科",
    "Gastroenterology": "消化内科",
    "心内科": "心血管内科",
    "心血管内科": "心血管内科",
    "Cardiology": "心血管内科",
    "神经内科": "神经内科",
    "Neurology": "神经内科",
    "呼吸内科": "呼吸内科",
    "Pulmonology": "呼吸内科",
    "肾内科": "肾内科",
    "Nephrology": "肾内科",
    "内分泌科": "内分泌科",
    "Endocrinology": "内分泌科",
    "康复医学科": "康复医学科",
    "Rehabilitation": "康复医学科",
    "急诊科": "急诊科",
    "Emergency": "急诊科",
    "中医": "中医科",
    "中医科": "中医科",
    "TCM": "中医科",
    "通用": "通用",
    "General": "通用",
    "UNKNOWN": "通用"
}
